<a href="https://colab.research.google.com/github/aaininssofiya06-commits/Final_Year_Project_RON97/blob/main/fyp2new.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
library(tidyverse)
library(readxl)
library(dplyr)
library(lubridate)
library(ggplot2)
library(zoo)
library(forecast)
library(tseries)
library(readr)

── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.2.1     ✔ readr     2.2.0
✔ forcats   1.0.1     ✔ stringr   1.6.0
✔ ggplot2   4.0.3     ✔ tibble    3.3.1
✔ lubridate 1.9.5     ✔ tidyr     1.3.2
✔ purrr     1.2.2
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

ERROR: Error in library(zoo): there is no package called ‘zoo’

# First part of my Analysis

Import dan Bersihkan Dataset

In [1]:
ron97 <- read.csv("/content/fuelprice 2.csv")

In [7]:
ron97

    series_type   date       ron95 ron97 diesel diesel_eastmsia ron95_budi95
1   level         30/3/2017  2.13  2.41  2.11   2.11            NA
2   level         6/4/2017   2.16  2.43  2.08   2.08            NA
3   level         13/4/2017  2.24  2.52  2.16   2.16            NA
4   level         20/4/2017  2.27  2.54  2.21   2.21            NA
5   level         27/4/2017  2.21  2.49  2.14   2.14            NA
6   level         4/5/2017   2.11  2.39  2.08   2.08            NA
7   level         11/5/2017  2.01  2.29  1.95   1.95            NA
8   level         18/5/2017  2.08  2.36  1.99   1.99            NA
9   level         25/5/2017  2.12  2.40  2.03   2.03            NA
10  level         1/6/2017   2.10  2.38  2.02   2.02            NA
11  level         8/6/2017   2.05  2.31  1.94   1.94            NA
12  level         15/6/2017  1.98  2.24  1.88   1.88            NA
13  level         22/6/2017  1.91  2.17  1.88   1.88            NA
14  level         29/6/2017  1.89  2.15  1.84   1.84            NA
15  level         6/7/2017   1.93  2.19  1.91   1.91            NA
16  level         13/7/2017  1.97  2.22  1.96   1.96            NA
17  level         20/7/2017  1.97  2.22  1.96   1.96            NA
18  level         27/7/2017  2.03  2.28  1.99   1.99            NA
19  level         3/8/2017   2.07  2.32  2.05   2.05            NA
20  level         10/8/2017  2.12  2.39  2.06   2.06            NA
21  level         17/8/2017  2.15  2.43  2.04   2.04            NA
22  level         24/8/2017  2.15  2.43  2.01   2.01            NA
23  level         31/8/2017  2.16  2.44  2.04   2.04            NA
24  level         7/9/2017   2.20  2.48  2.05   2.05            NA
25  level         14/9/2017  2.21  2.52  2.14   2.14            NA
26  level         21/9/2017  2.19  2.49  2.10   2.10            NA
27  level         28/9/2017  2.16  2.46  2.12   2.12            NA
28  level         5/10/2017  2.19  2.49  2.17   2.17            NA
29  level         12/10/2017 2.16  2.46  2.10   2.10            NA
30  level         19/10/2017 2.17  2.47  2.11   2.11            NA
⋮   ⋮             ⋮          ⋮     ⋮     ⋮      ⋮               ⋮
934 change_weekly 19/3/2026   0.00  0.70  0.80  0               0
935 change_weekly 26/3/2026   0.60  0.60  0.80  0               0
936 change_weekly 2/4/2026    0.00 -0.20  0.50  0               0
937 change_weekly 9/4/2026    0.40  0.40  0.70  0               0
938 change_weekly 16/4/2026  -0.25 -0.25 -0.75  0               0
939 change_weekly 23/4/2026  -0.15 -0.25 -0.85  0               0
940 change_weekly 30/4/2026   0.10  0.05  0.00  0               0
941 change_weekly 7/5/2026    0.05  0.00  0.05  0               0
942 change_weekly 14/5/2026  -0.15 -0.20 -0.30  0               0
943 change_weekly 21/5/2026   0.20  0.15  0.10  0               0
944 change_weekly 28/5/2026  -0.15 -0.20 -0.10  0               0
945 change_weekly 4/6/2026   -0.20 -0.30 -0.20  0               0
946 change_weekly 11/6/2026   0.00  0.00  0.00  0               0
947 change_weekly 18/6/2026   0.00  0.00 -0.30  0               0
948 change_weekly 25/6/2026  -0.25 -0.25 -0.30  0               0
949 change_weekly 1/7/2026   -0.10 -0.10 -0.10  0               0
950 change_weekly 9/7/2026    0.00  0.00  0.00  0               0
951 change_weekly 16/7/2026   0.05  0.00  0.10  0               0
952 change_weekly 23/7/2026   0.20  0.20  0.35  0               0
953 change_weekly 30/7/2026   0.20  0.20  0.20  0               0
954 change_weekly 6/8/2026   -0.05 -0.05 -0.05  0               0
955 change_weekly 13/8/2026  -0.15 -0.20 -0.10  0               0
956 change_weekly 20/8/2026   0.15  0.10  0.20  0               0
957 change_weekly 27/8/2026   0.05  0.05  0.05  0               0
958 change_weekly 3/9/2026   -0.05 -0.05 -0.05  0               0
959 change_weekly 10/9/2026   0.25  0.25  0.25  0               0
960 change_weekly 17/9/2026   0.35  0.35  0.35  0               0
961 change_weekly 24/9/2026   0.20  0.20  0.15  0               0
962 change_weekly 1/10/2026  -0.05 -0.05 -0.15  0               0
963 change_weekly 8/10/2026   0.15  0.15  0.00  0               0
    ron95_skps diesel_skds diesel_budi
1   NA         NA          khamis
2   NA         NA
3   NA         NA
4   NA         NA
5   NA         NA
6   NA         NA
7   NA         NA
8   NA         NA
9   NA         NA
10  NA         NA
11  NA         NA
12  NA         NA
13  NA         NA
14  NA         NA
15  NA         NA
16  NA         NA
17  NA         NA
18  NA         NA
19  NA         NA
20  NA         NA
21  NA         NA
22  NA         NA
23  NA         NA
24  NA         NA
25  NA         NA
26  NA         NA
27  NA         NA
28  NA         NA
29  NA         NA
30  NA         NA
⋮   ⋮          ⋮           ⋮
934 0          0
935 0          0
936 0          0
937 0          0
938 0          0
939 0          0
940 0          0
941 0          0
942 0          0
943 0          0
944 0          0
945 0          0
946 0          0
947 0          0
948 0          0
949 0          0
950 0          0           0
951 0          0           0
952 0          0           0
953 0          0           0
954 0          0           0
955 0          0           0
956 0          0           0
957 0          0           0
958 0          0           0
959 0          0           0
960 0          0           0
961 0          0           0
962 0          0           0
963 0          0           0

In [3]:
brent <- read.csv("/content/daily_0900.csv")

In [4]:
brent

      date       rate_type USD    EUR    JPY      GBP    SGD    AUD    CAD
1     2/5/2003   buying    3.8    4.2662 0.032016 6.1162 2.1473 NA     NA
2     2/5/2003   middle    3.8    4.2662 0.032023 6.1162 2.1478 NA     NA
3     2/5/2003   selling   3.8    4.2680 0.032030 6.1162 2.1482 NA     NA
4     5/5/2003   buying    3.8    4.2626 0.031943 6.0938 2.1505 NA     NA
5     5/5/2003   middle    3.8    4.2626 0.031945 6.0938 2.1510 NA     NA
6     5/5/2003   selling   3.8    4.2644 0.031946 6.0976 2.1510 NA     NA
7     6/5/2003   buying    3.8    4.2863 0.032046 6.1050 2.1668 NA     NA
8     6/5/2003   middle    3.8    4.2863 0.032053 6.1050 2.1668 NA     NA
9     6/5/2003   selling   3.8    4.2882 0.032059 6.1050 2.1673 NA     NA
10    7/5/2003   buying    3.8    4.3365 0.032294 6.1312 2.1858 NA     NA
11    7/5/2003   middle    3.8    4.3365 0.032301 6.1312 2.1863 NA     NA
12    7/5/2003   selling   3.8    4.3384 0.032307 6.1312 2.1867 NA     NA
13    8/5/2003   buying    3.8    4.3141 0.032584 6.0643 2.1867 NA     NA
14    8/5/2003   middle    3.8    4.3141 0.032591 6.0680 2.1872 NA     NA
15    8/5/2003   selling   3.8    4.3159 0.032598 6.0680 2.1877 NA     NA
16    9/5/2003   buying    3.8    4.3764 0.032409 6.0976 2.1810 NA     NA
17    9/5/2003   middle    3.8    4.3783 0.032416 6.0976 2.1815 NA     NA
18    9/5/2003   selling   3.8    4.3783 0.032423 6.0976 2.1820 NA     NA
19    12/5/2003  buying    3.8    4.3917 0.032479 6.0938 2.1896 NA     NA
20    12/5/2003  middle    3.8    4.3917 0.032486 6.0976 2.1901 NA     NA
21    12/5/2003  selling   3.8    4.3937 0.032493 6.0976 2.1906 NA     NA
22    13/5/2003  buying    3.8    4.3611 0.032351 6.1050 2.1891 NA     NA
23    13/5/2003  middle    3.8    4.3630 0.032358 6.1087 2.1896 NA     NA
24    13/5/2003  selling   3.8    4.3630 0.032365 6.1087 2.1906 NA     NA
25    16/5/2003  buying    3.8    4.3290 0.032626 6.1614 2.2109 NA     NA
26    16/5/2003  middle    3.8    4.3309 0.032633 6.1614 2.2109 NA     NA
27    16/5/2003  selling   3.8    4.3309 0.032640 6.1614 2.2114 NA     NA
28    19/5/2003  buying    3.8    4.4405 0.032866 6.1920 2.2095 NA     NA
29    19/5/2003  middle    3.8    4.4405 0.032873 6.1920 2.2099 NA     NA
30    19/5/2003  selling   3.8    4.4425 0.032880 6.1920 2.2104 NA     NA
⋮     ⋮          ⋮         ⋮      ⋮      ⋮        ⋮      ⋮      ⋮      ⋮
17223 1/10/2026  buying    4.0850 4.6287 0.025868 5.4196 3.1947 2.8358 2.8689
17224 1/10/2026  middle    4.0870 4.6318 0.025881 5.4228 3.1971 2.8380 2.8707
17225 1/10/2026  selling   4.0890 4.6349 0.025895 5.4261 3.1995 2.8402 2.8725
17226 2/10/2026  buying    4.0850 4.5883 0.025832 5.3848 3.1872 2.8256 2.8705
17227 2/10/2026  middle    4.0880 4.5925 0.025851 5.3898 3.1898 2.8281 2.8730
17228 2/10/2026  selling   4.0910 4.5966 0.025871 5.3948 3.1924 2.8306 2.8755
17229 5/10/2026  buying    4.0820 4.5894 0.025876 5.4038 3.1903 2.8386 2.8624
17230 5/10/2026  middle    4.0840 4.5921 0.025892 5.4066 3.1921 2.8402 2.8640
17231 5/10/2026  selling   4.0860 4.5947 0.025907 5.4095 3.1939 2.8418 2.8656
17232 6/10/2026  buying    4.0830 4.5815 0.025868 5.3981 3.1911 2.8454 2.8621
17233 6/10/2026  middle    4.0853 4.5849 0.025886 5.4021 3.1931 2.8474 2.8641
17234 6/10/2026  selling   4.0875 4.5882 0.025905 5.4061 3.1951 2.8494 2.8662
17235 7/10/2026  buying    4.0835 4.5927 0.025773 5.4151 3.1945 2.8495 2.8725
17236 7/10/2026  middle    4.0858 4.5961 0.025791 5.4189 3.1966 2.8514 2.8744
17237 7/10/2026  selling   4.0880 4.5994 0.025808 5.4227 3.1987 2.8534 2.8762
17238 8/10/2026  buying    4.0840 4.5729 0.025873 5.3933 3.1909 2.8404 2.8628
17239 8/10/2026  middle    4.0865 4.5765 0.025889 5.3975 3.1938 2.8434 2.8649
17240 8/10/2026  selling   4.0890 4.5801 0.025906 5.4016 3.1968 2.8464 2.8671
17241 9/10/2026  buying    4.0880 4.5855 0.025867 5.4101 3.1923 2.8469 2.8750
17242 9/10/2026  middle    4.0905 4.5887 0.025884 5.4142 3.1945 2.8490 2.8772
17243 9/10/2026  selling   4.0930 4.5919 0.025902 5.4183 3.1967 2.8512 2.8794
17244 12/10/2026 buying    4.0820 4.5776 0.025814 5.4082 3.1893 2.8529 2.8634
17245 12/10/2026 middle    4.0850 4.5813 0.025835 5.4124 3.1925 2.8554 2.8658
17246 12/10/2026 selling   4.0880 4.5851 0.025855 5.4166 3.1957 2.8579 2.8682
17247 13/10/2026 buying    4.0850 4.5585 0.025773 5.3947 3.1892 2.8403 2.8606
17248 13/10/2026 middle    4.0875 4.5617 0.025789 5.3996 3.1915 2.8422 2.8628
17249 13/10/2026 selling   4.0900 4.5648 0.025806 5.4045 3.1938 2.8442 2.8649
17250 14/10/2026 buying    4.0800 4.5704 0.025749 5.4105 3.1868 2.8511 2.8712
17251 14/10/2026 middle    4.0820 4.5731 0.025763 5.4133 3.1884 2.8533 2.8731
17252 14/10/2026 selling   4.0840 4.5757 0.025776 5.4162 3.1901 2.8555 2.8750
      CNY    ⋯ HKD      TWD      INR      PKR      NPR      SAR      AED
1     NA     ⋯ 0.487234 NA       NA       NA       NA       NA       NA
2     NA     ⋯ 0.487234 NA       NA       NA       NA       NA       NA
3     NA     ⋯ 0.487234 NA       NA       NA       NA       NA       NA
4     NA     ⋯ 0.487234 NA       NA       NA       NA       NA       NA
5     NA     ⋯ 0.487234 NA       NA       NA       NA       NA       NA
6     NA     ⋯ 0.487234 NA       NA       NA       NA       NA       NA
7     NA     ⋯ 0.487234 NA       NA       NA       NA       NA       NA
8     NA     ⋯ 0.487234 NA       NA       NA       NA       NA       NA
9     NA     ⋯ 0.487234 NA       NA       NA       NA       NA       NA
10    NA     ⋯ 0.487234 NA       NA       NA       NA       NA       NA
11    NA     ⋯ 0.487234 NA       NA       NA       NA       NA       NA
12    NA     ⋯ 0.487234 NA       NA       NA       NA       NA       NA
13    NA     ⋯ 0.487234 NA       NA       NA       NA       NA       NA
14    NA     ⋯ 0.487234 NA       NA       NA       NA       NA       NA
15    NA     ⋯ 0.487258 NA       NA       NA       NA       NA       NA
16    NA     ⋯ 0.487211 NA       NA       NA       NA       NA       NA
17    NA     ⋯ 0.487234 NA       NA       NA       NA       NA       NA
18    NA     ⋯ 0.487282 NA       NA       NA       NA       NA       NA
19    NA     ⋯ 0.487234 NA       NA       NA       NA       NA       NA
20    NA     ⋯ 0.487234 NA       NA       NA       NA       NA       NA
21    NA     ⋯ 0.487234 NA       NA       NA       NA       NA       NA
22    NA     ⋯ 0.487258 NA       NA       NA       NA       NA       NA
23    NA     ⋯ 0.487258 NA       NA       NA       NA       NA       NA
24    NA     ⋯ 0.487258 NA       NA       NA       NA       NA       NA
25    NA     ⋯ 0.487211 NA       NA       NA       NA       NA       NA
26    NA     ⋯ 0.487234 NA       NA       NA       NA       NA       NA
27    NA     ⋯ 0.487282 NA       NA       NA       NA       NA       NA
28    NA     ⋯ 0.487211 NA       NA       NA       NA       NA       NA
29    NA     ⋯ 0.487234 NA       NA       NA       NA       NA       NA
30    NA     ⋯ 0.487234 NA       NA       NA       NA       NA       NA
⋮     ⋮      ⋱ ⋮        ⋮        ⋮        ⋮        ⋮        ⋮        ⋮
17223 0.6093 ⋯ 0.520574 0.128028 0.042557 0.014730 0.026640 1.087883 1.112261
17224 0.6096 ⋯ 0.520839 0.128111 0.042580 0.014753 0.026654 1.088473 1.112836
17225 0.6099 ⋯ 0.521104 0.128194 0.042603 0.014777 0.026668 1.089064 1.113410
17226 0.6093 ⋯ 0.520621 0.127868 0.042402 0.014731 0.026504 1.087970 1.112170
17227 0.6097 ⋯ 0.521010 0.128022 0.042440 0.014755 0.026525 1.088827 1.113002
17228 0.6102 ⋯ 0.521399 0.128176 0.042477 0.014780 0.026546 1.089684 1.113834
17229 0.6088 ⋯ 0.520225 0.128071 0.042371 0.014719 0.026484 1.087171 1.111414
17230 0.6091 ⋯ 0.520484 0.128154 0.042398 0.014742 0.026499 1.087776 1.111988
17231 0.6094 ⋯ 0.520742 0.128237 0.042426 0.014766 0.026514 1.088381 1.112563
17232 0.6090 ⋯ 0.520286 0.128441 0.042394 0.014724 0.026499 1.087553 1.111716
17233 0.6093 ⋯ 0.520583 0.128572 0.042422 0.014746 0.026516 1.088181 1.112359
17234 0.6097 ⋯ 0.520880 0.128704 0.042450 0.014767 0.026532 1.088810 1.113002
17235 0.6091 ⋯ 0.520310 0.128372 0.042356 0.014729 0.026466 1.087831 1.111852
17236 0.6094 ⋯ 0.520617 0.128503 0.042383 0.014750 0.026483 1.088459 1.112495
17237 0.6097 ⋯ 0.520924 0.128634 0.042411 0.014771 0.026499 1.089088 1.113138
17238 0.6091 ⋯ 0.520440 0.128150 0.042186 0.014730 0.026372 1.087819 1.111958
17239 0.6095 ⋯ 0.520766 0.128289 0.042222 0.014753 0.026389 1.088514 1.112669
17240 0.6099 ⋯ 0.521091 0.128427 0.042259 0.014775 0.026406 1.089209 1.113380
17241 0.6099 ⋯ 0.520924 0.127930 0.042231 0.014745 0.026398 1.088537 1.112835
17242 0.6103 ⋯ 0.521245 0.128068 0.042259 0.014767 0.026415 1.089566 1.113652
17243 0.6107 ⋯ 0.521567 0.128207 0.042287 0.014790 0.026432 1.090594 1.114469
17244 0.6100 ⋯ 0.520106 0.127834 0.042174 0.014723 0.026373 1.086708 1.111383
17245 0.6104 ⋯ 0.520498 0.127988 0.042211 0.014747 0.026393 1.087651 1.112230
17246 0.6109 ⋯ 0.520890 0.128142 0.042249 0.014771 0.026413 1.088595 1.113078
17247 0.6103 ⋯ 0.520502 0.127804 0.042650 0.014747 0.026656 1.087622 1.112200
17248 0.6107 ⋯ 0.520840 0.127942 0.042678 0.014763 0.026674 1.088346 1.112911
17249 0.6112 ⋯ 0.521178 0.128081 0.042706 0.014779 0.026692 1.089069 1.113622
17250 0.6095 ⋯ 0.519858 0.126949 0.042817 0.014714 0.026761 1.086291 1.110869
17251 0.6098 ⋯ 0.520123 0.127070 0.042840 0.014738 0.026775 1.086881 1.111444
17252 0.6101 ⋯ 0.520387 0.127192 0.042863 0.014762 0.026789 1.087472 1.112019
      EGP    NZD    XDR
1     NA     NA     NA
2     NA     NA     NA
3     NA     NA     NA
4     NA     NA     NA
5     NA     NA     NA
6     NA     NA     NA
7     NA     NA     NA
8     NA     NA     NA
9     NA     NA     NA
10    NA     NA     NA
11    NA     NA     NA
12    NA     NA     NA
13    NA     NA     NA
14    NA     NA     NA
15    NA     NA     NA
16    NA     NA     NA
17    NA     NA     NA
18    NA     NA     NA
19    NA     NA     NA
20    NA     NA     NA
21    NA     NA     NA
22    NA     NA     NA
23    NA     NA     NA
24    NA     NA     NA
25    NA     NA     NA
26    NA     NA     NA
27    NA     NA     NA
28    NA     NA     NA
29    NA     NA     NA
30    NA     NA     NA
⋮     ⋮      ⋮      ⋮
17223 0.0786 2.3011     NA
17224 0.0787 2.3028 5.5573
17225 0.0788 2.3046     NA
17226 0.0780 2.2835     NA
17227 0.0781 2.2858 5.5431
17228 0.0783 2.2881     NA
17229 0.0780 2.2904     NA
17230 0.0781 2.2919 5.5301
17231 0.0782 2.2935     NA
17232 0.0779 2.2869     NA
17233 0.0780 2.2888 5.5266
17234 0.0781 2.2906     NA
17235 0.0780 2.2933     NA
17236 0.0782 2.2952 5.5345
17237 0.0783 2.2970     NA
17238 0.0779 2.2858     NA
17239 0.0780 2.2874 5.5257
17240 0.0782 2.2890     NA
17241 0.0779 2.2917     NA
17242 0.0781 2.2933 5.5297
17243 0.0782 2.2949     NA
17244 0.0776 2.2916     NA
17245 0.0777 2.2937 5.5281
17246 0.0778 2.2958     NA
17247 0.0775 2.2798     NA
17248 0.0776 2.2816 5.5315
17249 0.0778 2.2834     NA
17250 0.0772 2.2926     NA
17251 0.0773 2.2943 5.5214
17252 0.0774 2.2960     NA

In [5]:
usdmyr <- read.csv("/content/Crude Oil WTI Futures Historical Data 2.csv")

In [6]:
usdmyr

     Date       Price  Open   High   Low    Vol.    Change..
1    10/05/2026  89.43  91.77  91.88  88.74 274.98K -1.84%
2    10/02/2026  91.11  93.46  93.51  88.06 355.30K -1.90%
3    10/01/2026  92.87  90.40  93.68  88.79 337.18K 2.71%
4    09/30/2026  90.42  89.00  91.96  88.58 285.60K 1.16%
5    09/29/2026  89.38  93.53  94.74  88.78 335.17K -3.48%
6    09/28/2026  92.60  93.58  96.54  91.25 370.33K 0.21%
7    09/25/2026  92.41  94.75  94.75  91.51 345.78K -2.33%
8    09/24/2026  94.61  92.72  96.78  91.23 410.02K 2.66%
9    09/23/2026  92.16  89.89  93.06  88.71 370.71K 1.81%
10   09/22/2026  90.52  91.95  93.84  88.67 422.68K -2.00%
11   09/21/2026  92.37  96.75  97.22  91.19 339.73K -3.86%
12   09/18/2026  96.08  96.48  98.01  94.83 317.77K -5.72%
13   09/17/2026 101.91 102.18 102.47  99.10 265.97K -0.51%
14   09/16/2026 102.43 105.48 105.63 100.97 301.17K 1.67%
15   09/15/2026 100.75  97.40 101.69  97.16 255.79K 3.72%
16   09/14/2026  97.14  98.00 100.03  96.29 277.16K -2.91%
17   09/11/2026 100.05 104.32 104.46  98.48 399.14K -2.37%
18   09/10/2026 102.48  96.88 104.04  95.37 437.38K 6.69%
19   09/09/2026  96.05  94.31  96.93  93.76 325.21K 3.25%
20   09/08/2026  93.03  92.26  94.73  90.87 435.23K 0.55%
21   09/07/2026  92.52  92.70  93.30  90.88 100.39K 0.47%
22   09/06/2026  92.09  92.18  92.40  91.79         0.67%
23   09/04/2026  91.48  91.67  92.17  88.72 273.13K 0.20%
24   09/03/2026  91.30  90.70  93.14  89.57 324.52K 0.32%
25   09/02/2026  91.01  90.65  92.29  88.97 283.45K 0.88%
26   09/01/2026  90.22  86.31  90.97  86.13 331.11K 5.20%
27   08/31/2026  85.76  84.69  86.79  84.11 235.76K 2.83%
28   08/28/2026  83.40  83.67  83.78  82.25 167.62K -0.16%
29   08/27/2026  83.53  82.00  84.27  80.65 220.11K 1.58%
30   08/26/2026  82.23  81.11  83.31  79.62 255.92K -0.16%
⋮    ⋮          ⋮      ⋮      ⋮      ⋮      ⋮       ⋮
2477 05/01/2017 49.16  49.47  49.61  48.89  111.91K -0.93%
2478 04/28/2017 49.62  49.59  50.09  49.12  175.35K 0.63%
2479 04/27/2017 49.31  49.52  49.76  48.55  250.77K -1.30%
2480 04/26/2017 49.96  49.71  50.52  49.29  111.61K 0.81%
2481 04/25/2017 49.56  49.22  49.83  48.87  587.24K 0.67%
2482 04/24/2017 49.23  49.68  50.22  49.03  517.90K -0.79%
2483 04/21/2017 49.62  50.71  50.93  49.20  687.47K -1.29%
2484 04/20/2017 50.27  50.63  50.97  50.18  33.75K  -0.34%
2485 04/19/2017 50.44  52.36  52.65  50.09  133.17K -3.76%
2486 04/18/2017 52.41  52.75  52.85  52.10  202.04K -0.46%
2487 04/17/2017 52.65  52.97  53.21  52.55  326.34K -1.00%
2488 04/13/2017 53.18  52.85  53.39  52.82  480.84K 0.13%
2489 04/12/2017 53.11  53.40  53.76  52.71  629.81K -0.54%
2490 04/11/2017 53.40  53.13  53.45  52.70  598.00K 0.60%
2491 04/10/2017 53.08  52.31  53.18  52.29  565.44K 1.61%
2492 04/07/2017 52.24  51.70  52.94  51.49  796.44K 1.04%
2493 04/06/2017 51.70  50.80  51.82  50.77  473.02K 1.08%
2494 04/05/2017 51.15  51.18  51.88  50.74  651.40K 0.24%
2495 04/04/2017 51.03  50.24  51.30  49.88  532.05K 1.57%
2496 04/03/2017 50.24  50.69  50.83  50.12  440.72K -0.71%
2497 03/31/2017 50.60  50.32  50.85  49.90  527.61K 0.50%
2498 03/30/2017 50.35  49.60  50.47  49.27  580.67K 1.70%
2499 03/29/2017 49.51  48.47  49.63  48.38  548.62K 2.36%
2500 03/28/2017 48.37  47.89  48.74  47.80  502.38K 1.34%
2501 03/27/2017 47.73  48.12  48.28  47.08  466.18K -0.50%
2502 03/24/2017 47.97  47.67  48.20  47.54  421.03K 0.57%
2503 03/23/2017 47.70  48.15  48.48  47.58  499.88K -0.71%
2504 03/22/2017 48.04  48.16  48.32  47.01  680.85K 1.48%
2505 03/21/2017 47.34  47.93  48.73  47.23  28.08K  -1.82%
2506 03/20/2017 48.22  48.70  48.74  47.84  142.26K -1.15%

In [9]:
names(ron97)
names(brent)
names(usdmyr)

 [1] "series_type"     "date"            "ron95"           "ron97"
 [5] "diesel"          "diesel_eastmsia" "ron95_budi95"    "ron95_skps"
 [9] "diesel_skds"     "diesel_budi"

 [1] "date"      "rate_type" "USD"       "EUR"       "JPY"       "GBP"
 [7] "SGD"       "AUD"       "CAD"       "CNY"       "CHF"       "THB"
[13] "IDR"       "VND"       "KHR"       "MMK"       "PHP"       "BND"
[19] "KRW"       "HKD"       "TWD"       "INR"       "PKR"       "NPR"
[25] "SAR"       "AED"       "EGP"       "NZD"       "XDR"

[1] "Date"     "Price"    "Open"     "High"     "Low"      "Vol."     "Change.."

In [11]:
str(ron97)
str(brent)
str(usdmyr)

'data.frame':	963 obs. of  10 variables:
 $ series_type    : chr  "level" "level" "level" "level" ...
 $ date           : chr  "30/3/2017" "6/4/2017" "13/4/2017" "20/4/2017" ...
 $ ron95          : num  2.13 2.16 2.24 2.27 2.21 2.11 2.01 2.08 2.12 2.1 ...
 $ ron97          : num  2.41 2.43 2.52 2.54 2.49 2.39 2.29 2.36 2.4 2.38 ...
 $ diesel         : num  2.11 2.08 2.16 2.21 2.14 2.08 1.95 1.99 2.03 2.02 ...
 $ diesel_eastmsia: num  2.11 2.08 2.16 2.21 2.14 2.08 1.95 1.99 2.03 2.02 ...
 $ ron95_budi95   : num  NA NA NA NA NA NA NA NA NA NA ...
 $ ron95_skps     : num  NA NA NA NA NA NA NA NA NA NA ...
 $ diesel_skds    : num  NA NA NA NA NA NA NA NA NA NA ...
 $ diesel_budi    : chr  "khamis" "" "" "" ...
'data.frame':	17252 obs. of  29 variables:
 $ date     : chr  "2/5/2003" "2/5/2003" "2/5/2003" "5/5/2003" ...
 $ rate_type: chr  "buying" "middle" "selling" "buying" ...
 $ USD      : num  3.8 3.8 3.8 3.8 3.8 3.8 3.8 3.8 3.8 3.8 ...
 $ EUR      : num  4.27 4.27 4.27 4.26 4.26 ...
 $ JPY      : num  0.032 0.032 0.032 0.0319 0.0319 ...
 $ GBP      : num  6.12 6.12 6.12 6.09 6.09 ...
 $ SGD      : num  2.15 2.15 2.15 2.15 2.15 ...
 $ AUD      : num  NA NA NA NA NA NA NA NA NA NA ...
 $ CAD      : num  NA NA NA NA NA NA NA NA NA NA ...
 $ CNY      : num  NA NA NA NA NA NA NA NA NA NA ...
 $ CHF      : num  2.82 2.82 2.82 2.82 2.82 ...
 $ THB      : num  NA NA NA NA NA NA NA NA NA NA ...
 $ IDR      : num  NA NA NA NA NA NA NA NA NA NA ...
 $ VND      : num  NA NA NA NA NA NA NA NA NA NA ...
 $ KHR      : num  NA NA NA NA NA NA NA NA NA NA ...
 $ MMK      : num  NA NA NA NA NA NA NA NA NA NA ...
 $ PHP      : num  NA NA NA NA NA NA NA NA NA NA ...
 $ BND      : num  NA NA NA NA NA NA NA NA NA NA ...
 $ KRW      : num  NA NA NA NA NA NA NA NA NA NA ...
 $ HKD      : num  0.487 0.487 0.487 0.487 0.487 ...
 $ TWD      : num  NA NA NA NA NA NA NA NA NA NA ...
 $ INR      : num  NA NA NA NA NA NA NA NA NA NA ...
 $ PKR      : num  NA NA NA NA NA NA NA NA NA NA ...
 $ NPR      : num  NA NA NA NA NA NA NA NA NA NA ...
 $ SAR      : num  NA NA NA NA NA NA NA NA NA NA ...
 $ AED      : num  NA NA NA NA NA NA NA NA NA NA ...
 $ EGP      : num  NA NA NA NA NA NA NA NA NA NA ...
 $ NZD      : num  NA NA NA NA NA NA NA NA NA NA ...
 $ XDR      : num  NA NA NA NA NA NA NA NA NA NA ...
'data.frame':	2506 obs. of  7 variables:
 $ Date    : chr  "10/05/2026" "10/02/2026" "10/01/2026" "09/30/2026" ...
 $ Price   : num  89.4 91.1 92.9 90.4 89.4 ...
 $ Open    : num  91.8 93.5 90.4 89 93.5 ...
 $ High    : num  91.9 93.5 93.7 92 94.7 ...
 $ Low     : num  88.7 88.1 88.8 88.6 88.8 ...
 $ Vol.    : chr  "274.98K" "355.30K" "337.18K" "285.60K" ...
 $ Change..: chr  "-1.84%" "-1.90%" "2.71%" "1.16%" ...

CLEAN RON97 DATA

In [12]:
# Semak kategori series_type
table(ron97$series_type, useNA = "ifany")

change_weekly         level
          481           482

In [16]:
# Kekalkan harga sebenar sahaja

ron97_clean <- ron97 %>%
  filter(series_type == "level") %>%
  transmute(
    date = dmy(date),
    price_ron97 = as.numeric(ron97)
  ) %>%
  arrange(date)

In [14]:
install.packages(c("dplyr", "lubridate"))

Installing packages into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

In [15]:
library(dplyr)
library(lubridate)

Attaching package: ‘dplyr’


The following objects are masked from ‘package:stats’:

    filter, lag


The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union



Attaching package: ‘lubridate’


The following objects are masked from ‘package:base’:

    date, intersect, setdiff, union